### ISSUE TITLE
Set the distance from the photon field

### ISSUE THREAD

**Issue by cosimoNigro** [andreatramacere/jetset#15]
Hello @andreatramacere,

how do I fix the distance of the blob from the target photon field? 
For example if I want to consider the external Compton on the dusty torus I get, from the `show_pars()`:
```python-------------------------------------------------------------------------------------------------------------------
model parameters:
 Name             | Type                 | Units            | value         | phys. boundaries              | log
-------------------------------------------------------------------------------------------------------------------
 B                | magnetic_field       | G                | +1.000000e+00 | [+0.000000e+00,No           ] | False 
 N                | electron_density     | cm^-3            | +1.302546e+03 | [+0.000000e+00,No           ] | False 
 R                | region_size          | cm               | +1.600000e+01 | [+0.000000e+00,+3.000000e+01] | True 
 R_DT             | DT                   | cm               | +5.000000e+18 | [+0.000000e+00,No           ] | False 
 T_DT             | DT                   | K                | +1.000000e+02 | [+0.000000e+00,No           ] | False 
 beam_obj         | beaming              |                  | +1.000000e+01 | [+1.000000e+00,No           ] | False 
 gmax             | high-energy-cut-off  | Lorentz-factor   | +1.000000e+05 | [+1.000000e+00,+1.000000e+15] | False 
 gmin             | low-energy-cut-off   | Lorentz-factor   | +1.000000e+02 | [+1.000000e+00,+1.000000e+05] | False 
 p                | HE_spectral_slope    |                  | +2.800000e+00 | [-1.000000e+01,+1.000000e+01] | False 
 tau_DT           | DT                   |                  | +1.000000e-01 | [+0.000000e+00,+1.000000e+00] | False 
 z_cosm           | redshift             |                  | +6.959965e-02 | [+0.000000e+00,No           ] | False 
-------------------------------------------------------------------------------------------------------------------


```

How do I evaluate the spectrum from different distances of the blob from the torus?
The Broad Line Region seems to have this `R_H`
```python
 R_H              | Disk                 | cm               | +1.000000e+17 | [+0.000000e+00,No           ] | False
```
But I do not find the equivalent for the Torus.

Cheers!

**Comment by andreatramacere** [comment]
Hi Cosimo, I need to add R_H to the DT in the python interface, thanks for spotting this problem! I will do it as soon as possible. Is it urgent? 
Thanks a lot for the feedback

**Comment by cosimoNigro** [comment]
No it is not urgent.
Thanks!

**Comment by andreatramacere** [comment]
Quick fix:
`j=Jet()

j.add_EC_component('EC_DT')

j._blob.R_H=1e21
`
R_H will not be show in show_pars() but will be effective. It is the distance of the  blob from the BH in cm

**Comment by cosimoNigro** [comment]
Thank you!

**Comment by cosimoNigro** [comment]
Ehm, I think it is not working 
```python
from jetset.jet_model import Jet
import matplotlib.pyplot as plt

jet = Jet(name="test", electron_distribution="pl")
jet.add_EC_component('EC_DT')

fig = plt.figure()

for r in (1e16, 1e17, 1e18):
    jet._blob.R_H = r
    jet.eval()
    ene, sed = jet.get_SED_points(name="EC_DT")
    plt.loglog(ene, sed, label=f"r={r}")

plt.ylim([1e-15, 1e-12])
plt.legend()
plt.show()
fig.savefig("test.png")  
```
![test](https://user-images.githubusercontent.com/26409711/56095408-e9cf3e00-5edc-11e9-9089-eb7cf041ac83.png)

But really no rush, just wanted to point out.

**Comment by andreatramacere** [comment]
As long as you are within the Torus radius, the photon field does not change (Ghisellini & Madau 1996). To see the effect you  have to start to approach R_DT (that as default is 5e18). But I have to admit that I did not check if the transition between R_H~<R_DT and R_H>~R_DT is correct. There is transition region that should  be interpolated.


``` python
 from jetset.jet_model import Jet
import matplotlib.pyplot as plt

jet = Jet(name="test", electron_distribution="pl")
jet.add_EC_component('EC_DT')

fig = plt.figure()

for r in (1e16, 1e17, 1e18,4E18,5E18,6E18,1E19,2E19):
    jet._blob.R_H = r
    jet.eval()
    ene, sed = jet.get_SED_points(name="EC_DT")
    plt.loglog(ene, sed, label=f"r={r}")

plt.ylim([1e-19, 1e-12])
plt.legend()
plt.show()
fig.savefig("test.png")
```
![image](https://user-images.githubusercontent.com/12498415/56096162-d7f19900-5ee4-11e9-9142-289244ab06d1.png)

**Comment by abhradeep-1996** [comment]
Hello @andreatramacere ,
Can you please tell me actually what is this disk parameter R_H and what is its physical meaning?
I found that the EC_disk component is very sensitive to the change in R_H. As I have no clue about this parameter, I am not confident enough to change its value.
It will be helpful if you give me some idea about R_H and its usage.

**Comment by andreatramacere** [comment]
Hi @abhradeep-1996,
R_H is the distance between the BH and the emitting region. If R_H <R_BLR_in
 (the BLR is modelled as a spherical shell with  inner radius R_BLR_in and outer radius R_BLR_out) or  R_H <R_DT (the photon field of the Dusty Torus is modelled as sphere of radius R_DT, even though the name seems misleading), you should get a constant energy density from the external photon field. As long as R_H start to get larger then R_BLR or R_DT, then the corresponding EC component should start to decrease. Of course, if R_H >R_BLR_out but R_H<D_T, then only the EC from the dusty torus will decrease. Anyhow, I am releasing a new version of the code, with an improved documentation and also a better implementation of the external Compton.
Please, do not hesitate to contact me if you have any doubt, you can also share jupyther notebooks if it is more convenient to you.
Cheers
 Andrea
![image](https://user-images.githubusercontent.com/12498415/69339422-8f157600-0c65-11ea-88c6-c0a35d41776a.png)

**Comment by abhradeep-1996** [comment]
Thank you very much Sir for solving my confusion !

**Comment by andreatramacere** [comment]
@cosimoNigro @abhradeep-1996  There is new release: v1.1.0 ,with major updates in particular for the EC ,the astropy units integration, and the documentation. Now it is possible to install directly from conda (for linux and mac osx )see the docs for instructions:
https://jetset.readthedocs.io/en/1.1.0/
