### ISSUE TITLE
Issue with external emitters class.

### ISSUE THREAD

**Issue by Noatino** [andreatramacere/jetset#36]
Hi Adrea,

Currently I start to learn the custom emitters distribution. So I follow the steps in the page:
[Custom emitters distribution](https://jetset.readthedocs.io/en/latest/user_guide/custom_emitters_distr/custom_emitters.html#custom-emitters-guide)

But, when I try to start, I've a module error (my python  file is called ElectronDistribution as you can see):

```
  File "ElectronDistribution.py", line 4, in <module>
    from jetset.jet_emitters import EmittersDistribution
ModuleNotFoundError: No module named 'jetset.jet_emitters'

```
So, I don't know of this is a error due a bad installation (I follow the instruction for conda in a linux machine), so I will apreciatted any kind of help from yours. 

Hope to hear about from you soon.

My best,

Antonio.

**Comment by andreatramacere** [comment]
Dear Antonio,
which version are you using?
Probably you are using version<1.1.2.
Try to install version 1.1.2 that is the version where EmittersDistribution has  been introduced.
If you know how to install from source, please, install this specific version:
https://github.com/andreatramacere/jetset/archive/1.1.2c.tar.gz
which is fixing some minor bugs in v1.1.2
Cheers
  Andrea

**Comment by Noatino** [comment]
Hi Adrea,

It works! Thanks a lot for the help.

My best,

Antonio.
