### ISSUE TITLE
upload host galaxy template from a file

### ISSUE THREAD

**Issue by me-astro** [andreatramacere/jetset#38]
Hi,
Thanks for this very nice tool.
Just a question about the host galaxy template. If I want to upload a template from a file, where should I give it to the model? For example, when I do 

mm,best_fit=my_shape.sync_fit(check_host_gal_template=True,
                  Ep_start=None,
                  minimizer='lsb',
                  silent=True,
                  fit_range=[10. , 21.])

my_shape.IC_fit(fit_range=[23., 29.],minimizer='minuit',silent=True)
p=my_shape.plot_shape_fit()
p.rescale(y_min=-15)

It checks the host galaxy and returns the parameters. But I want to give the template from a file.
Can you please help with this ?

**Comment by andreatramacere** [comment]
Hi,
in principle it is very easy to build a model with arbitrary templates (even if I still need to write no notebook for the documentation). But for the sedshaper, in the current version, the code will use the default one. I will add the possibility to load a custom shape in the sedshaper, as new feature in the new release. But if you want to  do it with the current release,  I can make a new branch, then you should checkout that branch, and install from the source. On the contrary, if you want to load the template when you do the final model minimisation, then it can be done easily also with the current version.

**Comment by me-astro** [comment]
Hi Andrea,

Thanks for your answer. Can you please help me to understand how to load the template during the final minimization ?

Thanks a lot!

**Comment by andreatramacere** [comment]
Hi,
this is the link to notebook wit the example: https://drive.google.com/drive/folders/1G3TAnNrEpAcTbZq20M7Cwp4jVWpH5bv5
There are some caveats in boldface in the notebook. The most importanti is that, waiting for the new release, now you should prepare your template with a scale on x and y axis as much as possible close to that of the custom one, and you have to take the starting value of the nuFnu_p from the sedshaping stage. Everything is in the notebook, I am attaching also the custom template that is loaded, that by the way is the same of the default, but it proofs that it works. Please, let me know if you need further support. I any case, I will make a prerelease soon, with the custom model enabled also in the sed shaping process.

**Comment by me-astro** [comment]
Thank you very much Andrea!

It works, thanks for your help.

**Comment by andreatramacere** [comment]
Good,
so I close the issue. I will send you a notice when I have a prototipe with the new branch to test.
Cheers
  Andrea
