### ISSUE TITLE
Using JetSet, first steps 

### ISSUE THREAD

**Issue by mmanganaro** [andreatramacere/jetset#50]
Dear Andrea,
I have installed JetSet from anaconda on my Linux machine (Ubuntu 18 and python 3.8) and tested it successfully following the installation guide. I am now going trough the tutorials and I get stuck in the "QuickStart_1" notebook because of the following error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-e2943891883f> in <module>
----> 1 from jetset.jet_model import Jet
      2 my_jet=Jet(name='my_jet',electron_distribution='lppl',)

~/Software/jetset-stable/jetset/jet_model.py in <module>
     15 import warnings
     16 
---> 17 from .jet_spectral_components import JetSpecComponent, SpecCompList
     18 
     19 on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

~/Software/jetset-stable/jetset/jet_spectral_components.py in <module>
     24         from .mock import jetkernel as BlazarSED
     25 else:
---> 26     from jetkernel import jetkernel as BlazarSED
     27 
     28 from . import spectral_shapes

~/Software/jetset-stable/jetkernel/jetkernel.py in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _jetkernel
     14 else:
     15     import _jetkernel

ImportError: cannot import name '_jetkernel' from 'jetkernel' (/home/marina/Software/jetset-stable/jetkernel/__init__.py)
***************************************************************************************************************************************
Do you maybe have a suggestion? 
Thanks a lot in advance!
Marina

**Comment by andreatramacere** [comment]
Hi Marina,
could you please tell me which version are you using?
Thanks,
 Andrea

**Comment by andreatramacere** [comment]
Dear Marina,
Are you sure that you are not running the notebook from the same directory where you installed
the code?
In case you need support, I can organize a quick zoom meeting.
Let me know,
Cheers
  Andrea

**Comment by mmanganaro** [comment]
Hello Andrea,
thanks for your quick reply: I looked into the folder /dist and find this file: jetset-1.1.2.post1-py3.8-linux-x86_64.egg
So I suppose I have this version: jetset-1.1.2
The notebook is inside the folder /notebooks in the installation directory. 
Sure a zoom meeting would be great if you have time, I send you a private message!
Cheers
Marina

**Comment by andreatramacere** [comment]
@mfuphi, there Is a chance that you have a version of iminuit not compatibile with the version of jetset. You can try to downgrade iminuit to version<2.0, or you can indtallb

**Comment by mfuphi** [comment]
I'm using version 1.1.2. First I tried installing from the binaries but ran into this message:
`
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
`
==================================================================
So I installed it from the source folder  "jetset-master.zip". 
My python is pointing to the JetSe environment, see below
`
(jetset) mfuphi@mfuphi-Lenovo-ideapad-330-15IKB:~$ which python
/home/mfuphi/anaconda3/envs/jetset/bin/python
`

**Comment by andreatramacere** [comment]
@mfuphi, try to install form source from the develop branch, this Is the latest version. For the documentario use: https://andreatramacere.github.io/jetsetdoc/html/index.html
Let me know

**Comment by mfuphi** [comment]
Hi @andreatramacere, thank you. It turns out my version of iminuit was incompatible, thank you for pointing this out. I installed the correct one and it worked. I just double-checked the rest of the dependencies to make sure they are all there and that they are correct versions. My code is working again, thank you!

**Comment by andreatramacere** [comment]
@mfuphi, I'am glad It worked! I suggest you to install, in a separate environment the new version. This is the pre release of version 1.2.0. There are several new features. only the documentation for the temporal evolution needs to be updated. Let know if you need help to install it. Source code and binaries are in the realeses section of the GitHub repo, release 1.2.0rc8. instructions to install are in the wikipage of the git repo. Documentation is here: https://andreatramacere.github.io/jetsetdoc/html/index.html

**Comment by mfuphi** [comment]
Thank you, @andreatramacere, I will add the new version.
