### ISSUE TITLE
How to save the fitted SED component values ? 

### ISSUE THREAD

**Issue by krishnamohana** [andreatramacere/jetset#76]
Hi,
I am Krishna, a phd scholar from Manipal, Karnataka, India, working in research area of AGN.
I wanted to know that how can I save the fitted SED values (theoretical model lines) into a txt file in JetSet?
so that one can plot else where. Your response in this matter would be much 
appreciated. I am sincerely waiting for your reply.

**Comment by andreatramacere** [comment]
Dear Krishna, thanks a lot for using jetset.
The information you need is at the end of this section of the documentation: https://jetset.readthedocs.io/en/latest/user_guide/documentation_notebooks/jet_model_phys_SSC/Jet_example_phys_SSC.html#accessing-individual-spectral-components
I remind you that the new version, 1.2.2 has been released, and I suggest you to update to it.
Cheers
  Andrea

**Comment by krishnamohana** [comment]
Thanks a lot andrea :)

**Comment by maitreyakun** [comment]
Hello, 

I have been experiencing the same issue while using ```jetset```. I was trying to fit an SED using only SSC Fitting with LSB (as described [here](https://jetset.readthedocs.io/en/latest/user_guide/documentation_notebooks/model_fit_1/Jet_example_model_fit.html)) and so, unlike the previous link that you posted, I am not using any ```my_jet``` per se. In that case, how can I find the array for synch, SSC, etc., for further analyses? Thanks.
