### ISSUE TITLE
What‘s the meaning of "beaming factor"

### ISSUE THREAD

**Issue by bluecandyrain** [andreatramacere/jetset#86]
I'm sorry to ask you about the simple question, but I do feel confusing. I know beaming effect and Doppler factor, but I heard about "beaming factor" little.  In your document it's said that "beaming factor" is calculated by the bulk Lorenz factor and viewing angle, I know the two, but I can't find the calculating  formula. I checked in a dictionary and find no "beaming factor". I have read some papers that define the "beaming factor" as a parameter that relate to jet open angle only. So I guess that "beaming factor" is a more customized noun.

**Comment by andreatramacere** [comment]
Hi @bluecandyrain, you can find a pedagogical derivation here: https://arxiv.org/pdf/1202.5949 in Chapter 3, the formula is given in Eq. 3.15. The beaming factor is the result of special relativity and doppler effect. This definition holds for spherical sources, such as a blob. For more complex cases, such as expanding shell in GRBs, with a significant variation of the bulk factor within a short timescale, there is further effect given by the relation between the jet opening angle and the bulk Lorentz factor, which impacts on the fraction of the visible jet, and this is typically mentioned as beaming fraction. In the code I use only the former definition, but if when I will implement the GRB plugin, I will take into account also the latter.

**Comment by bluecandyrain** [comment]
@andreatramacere I see it. Thank you!
